[package]
name = "single-line"
version = "0.1.0"
edition = "2021"
authors = ["Joe <joe@cluml.com>"]
readme = "README.md"
repository = "https://github.com/dongju93/single-line-logs"

[dependencies]
regex = "1.9.5"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
